### PR TITLE
keys panel in advanced tab

### PR DESCRIPTION
**Pull request by ankit-m**
I have added the keys panel in the **advanced tab** instead of the *translation tab* because there is already a field of keys there. It would cause confusion to the user.

keys

Please suggest changes if needed.

### CODE REVIEW

**Comment by Ceilican** [comment]
"Cliend" --> "Client"

**Comment by Ceilican** [comment]
Should we add buttons like "Get Google Key" at the right side of the text fields for the keys?

**Comment by ankit-m** [comment]
new_keys

**Comment by Ceilican** [comment]
Thanks!

**Pull request merged**
