### PR TITLE
pagination for blacklisted words and websites

### PR DESCRIPTION
**Pull request by ankit-m**
pagination

It limits to 4 entries per page and automatically creates new pages as per the entries.

### CODE REVIEW

**Comment by Ceilican** [comment]
Thanks!

**Comment by Ceilican** [comment]
And what happens when the number of pages is so large that it doesn't fit in the available horizontal space?

**Comment by ankit-m** [comment]
@Ceilican I am working on that edge case. I will mostly add a next button. and limit the number of pages shown.

**Comment by rohankatyal29** [comment]
Can we use a fixed sized window with scroll in it? This style breaks ui
with every new addition. The dimensions of the box should remain static

On Thursday 26 May 2016, Ankit Muchhala <notifications@github.com> wrote:

> [image: pagination]
> <https://cloud.githubusercontent.com/assets/9019878/15584110/b621393e-2396-11e6-88ea-52699e40f60c.png>
>
> It limits to 4 entries per page and automatically creates new pages as per
> the entries.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/OiWorld/MindTheWord/pull/118
> Commit Summary
>
>    - pagination for blacklisted words and websites
>
> File Changes
>
>    - *M* lib/scripts/controllers/options.js
>    <https://github.com/OiWorld/MindTheWord/pull/118/files#diff-0> (12)
>    - *A* lib/scripts/filters/startFrom.js
>    <https://github.com/OiWorld/MindTheWord/pull/118/files#diff-1> (10)
>    - *M* lib/styles/main.css
>    <https://github.com/OiWorld/MindTheWord/pull/118/files#diff-2> (9)
>    - *M* lib/views/options.html
>    <https://github.com/OiWorld/MindTheWord/pull/118/files#diff-3> (18)
>
> Patch Links:
>
>    - https://github.com/OiWorld/MindTheWord/pull/118.patch
>    - https://github.com/OiWorld/MindTheWord/pull/118.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OiWorld/MindTheWord/pull/118>
>


-- 
Regards,
Rohan Katyal

Please ignore the typos and brevity, email sent using a small form factor
device

**Comment by ankit-m** [comment]
@rohankatyal29 I am not sure about scrolling. But the dimensions of the box could be made static. That will solve the problem of box resizing.

**Pull request merged**
