### PR TITLE
Added Malayalam(ml) translation for Description

### PR DESCRIPTION
**Pull request by anikraj1994**
Accurate translation for the description in Malayalam(ml).

### CODE REVIEW

**Comment by ceilican** [comment]
Thank you! Just to be sure, you are a speaker of Malayalam, right?

**Comment by anikraj1994** [comment]
Yes, I do speak Malayalam 😄 I want to help out with making an android app. Do i start with the repo here or the one at gitlab?

**Comment by ceilican** [comment]
Use the gitlab repo, please!  There is an issue there where we are discussing the android app. Have a look on the Carbon Footprint repo as well, because we are also discussing ideas related to android apps in one of the issues there, and those ideas could be relevant for MTW as well.

**Comment by ceilican** [comment]
And thanks again for your interest.

**Comment by anikraj1994** [comment]
Will see what we can do to make this app work. 😄

**Pull request merged**
