### PR TITLE
[Enhancement] User can blacklist words using context menu

### PR DESCRIPTION
**Pull request by rohankatyal29**
Phrases with a space in them aren't blacklisted
Reorganization of context menu under parent item

screen shot 2016-03-09 at 8 40 50 am
screen shot 2016-03-09 at 8 40 41 am

### CODE REVIEW

**Comment by Ceilican** [comment]
That looks very nice, @rohankatyal29 !
Could you rebase it, so that I can easily merge it?

**Comment by Ceilican** [comment]
@Stormteller , have a look on this. I think adding new words and translations to the user-defined translations could be done in a way similar to this.

**Comment by rohankatyal29** [comment]
Thanks @Ceilican , please have a look at #83.

I am closing this PR.

**Comment by Stormteller** [comment]
@Ceilican Ow, this way is really better than mine. So I will refuse my idea and do it in this way

**Pull request closed without merging**
