### PR TITLE
dist folder

### PR DESCRIPTION
**Pull request by ankit-m**
Adding distribution folder and related gulp tasks. This folder will contain the final minified code which should be used for deployment.

**Note:** You can use the code in this folder without installing any of npm or jspm dependencies. 

To create a new distribution copy. Run

```shell
gulp build
```

This will clean the dist folder and put in the new compressed code.

### CODE REVIEW

**Comment by Ceilican** [comment]
Thanks, Ankit! Could you rebase this PR to make it automatically mergeable?

**Comment by Ceilican** [comment]
Also, could you add the instruction about "gulp build" to CONTRIBUTE.md (or some other file, if you find it more appropriate)?

**Comment by ankit-m** [comment]
@Ceilican I have made the changes in CONTRIBUTE.md

**Comment by Ceilican** [comment]
Thanks!

**Pull request merged**
