### PR TITLE
update html styling according to Google style guide

### PR DESCRIPTION
**Pull request by ankit-m**
> Indent by 2 spaces at a time.
Don’t use tabs or mix tabs and spaces for indentation.

> Although fine with HTML, do not close void elements, i.e. write `<br>`, not `<br />`.

### CODE REVIEW

**Comment by Ceilican** [comment]
This PR became unmergeable. Could you rebase it?

**Comment by ankit-m** [comment]
@Ceilican the PR is now mergeable.

**Comment by Ceilican** [comment]
@ankit-m : it still looks unmergeable to me.

**Comment by ankit-m** [comment]
@Ceilican it became unmergeable because of the PRs merged. I ll update it again.

**Comment by ankit-m** [comment]
@Ceilican mergeable now.

**Comment by Ceilican** [comment]
Thanks!

**Pull request merged**
