### PR TITLE
automatic blacklisting UI

### PR DESCRIPTION
**Pull request by ankit-m**
This PR adds UI elements for users to change automatic blacklisting settings.

automatic_defer ui

### CODE REVIEW

**Comment by Ceilican** [comment]
Thanks!

**Comment by Ceilican** [comment]
Is the user able to deactivate automatic blacklisting?

**Comment by ankit-m** [comment]
No the user is not, but I can definitely add that feature.

**Comment by Ceilican** [comment]
I think that would be a good idea.

**Pull request merged**
