### PR TITLE
redesign options page.

### PR DESCRIPTION
**Pull request by ankit-m**
new improved ui

### CODE REVIEW

**Comment by Ceilican** [comment]
Thanks!

**Comment by Ceilican** [comment]
@ankit-m One of the tests is failing now. It is clearly a problem in the test, not in the code. The test needs to be fixed.

**Comment by ankit-m** [comment]
@Ceilican the tests aren't wrong. In fact, I set the test to see whether default translator is set `Yandex`. In the latest set of changes, we removed default translator. Hence it shows the error. 

err_test

**Comment by ankit-m** [comment]
I will make the changes in the test and raise a PR.

**Comment by Ceilican** [comment]
>  In fact, I set the test to see whether default translator is set Yandex. In the latest set of changes, we removed default translator. Hence it shows the error.

Yes, that's what I meant.

**Pull request merged**
