### PR TITLE
Refactored mtw

### PR DESCRIPTION
**Pull request by ankit-m**
**Note:** The old `README.md` has been renamed to `README_old.md`. These will be combined in later PRs.

The following features/bugs remain:
- [ ] Context menu features 
- [x] Punctuation filtering in source words
- [ ] Unit testing and E2E testing
- [ ] Travis CI integration
- [ ] Contribute page

Features
------------
1. New UI
2. Efficient message passing architecture
3. New development environment
4. Modular code for faster integration of changes

Screenshots
-----------------
adv_settings
translation_settings

### CODE REVIEW

**Comment by rohankatyal29** [comment]
Just raised a PR for removing punctuation marks, we can remove that from
the list

Regards,
Rohan Katyal

*Linkedin:* <http://goog_459360573>*in.linkedin.com/in/rohankatyal/
<http://in.linkedin.com/in/rohankatyal/>
<http://in.linkedin.com/pub/rohan-katyal/7a/704/a9b/>*
*E:* rohan12086@iiitd.ac.in
*M:* +919910678001

**Comment by ankit-m** [comment]
@rohankatyal29 I have already changed my repository to my fork of MTW. Can you generate a PR here after @Ceilican merges it?

**Comment by Ceilican** [comment]
Thanks!

**Comment by Ceilican** [comment]
@rohankatyal29 where is the PR for removing punctuation marks?  I couldn't find it here in the main fork.

**Pull request merged**
