### PR TITLE
Google translate

### PR DESCRIPTION
**Pull request by ankit-m**
This PR adds support for Google Translate API. 

**Notes** 
1. Google does not allow more than 100 characters per second translations. This sometimes might lead to no translations being fetched. This error is caught and logged on the console.
2. Google allows 128 strings to translated in one call. This forces us to make multiple API calls for one page (i.e. if the number of words is greater than 128). Even if a single API call fails, no translations will be shown.

### CODE REVIEW

**Comment by Ceilican** [comment]
I noticed that no changes to the options page were committed. I am wondering where the user will insert the Google API key... Could you tell me? Could you show me a screenshot of the options page?

**Comment by Ceilican** [comment]
> 2. Google allows 128 strings to translated in one call. This forces us to make multiple API calls for one page (i.e. if the number of words is greater than 128). Even if a single API call fails, no translations will be shown.

Wouldn't it make more sense to show the translations corresponding to the successful API calls?

**Comment by rohankatyal29** [comment]
@Ceilican: There is already support for the user to save the key

screen shot 2016-06-08 at 8 58 30 am

**Comment by Ceilican** [comment]
Thanks!

**Comment by ankit-m** [comment]
Thanks @rohankatyal29 !

@Ceilican It is because `Promise.all()` function. It is fast fail function and throws as soon as any one promise fails. I will still try and retrieve the partial results.

**Pull request merged**
